/* Program:
	Author:
	Class:
	Date:
	Description:
	I certify that the code below is my own work.
	Exception(s): N/A
*/
#include <iostream>
#include <fstream>
#include <string>
#include <vector>

using namespace std;

void getPints(double pints[], int& hours);
double getAverage(double pints[], int hours);
double getHigh(double pints[], int hours);
double getLow(double pints[], int hours);
void displayInfo(int hours, double averagePints, double highestPints, double lowestPints);

const int MAX_HOURS = 24;

int main()
{
	
	double pints[MAX_HOURS] = { };
	int hours = 0;
	double averagePints, highestPints, lowestPints;

	getPints(pints, hours);
	cout << "Hours: " << hours << endl;
	cout << "First Value: " << pints[0] << endl;
	cout << "Last Value: " << (hours > 0 ? pints[hours - 1] : 0) << endl;
	averagePints = getAverage(pints, hours);
	highestPints = getHigh(pints, hours);
	lowestPints = getLow(pints, hours);
	displayInfo(hours, averagePints, highestPints, lowestPints);

	return 0;
}

void getPints(double pints[], int& hours)
{
	ifstream bloodInFile;
	bloodInFile.open("bloodDrive.txt");
	
	if (!bloodInFile.is_open())
	{
		cout << "Error opening bloodDrive.txt" << endl;
		
		return;
	}
	hours = 0;
	int a;


	while(bloodInFile >> a && hours < MAX_HOURS)
	{
		pints[hours++] = a;
		
	}

	bloodInFile.close();

}

double getAverage(double pints[], int hours)
{
	double totalPints = 0;
	double averagePints;

	for (int counter = 0; counter < hours; counter++)
	{
		totalPints += pints[counter];
	}

	averagePints = totalPints / hours;
	return averagePints;
}

double getLow(double pints[], int hours)
{
	double lowest = pints[0];

	for (int index = 1; index < hours; index++)
	{
		if (pints[index] < lowest)
		{
			lowest = pints[index];
		}
	}

	return lowest;
}


double getHigh(double pints[], int hours)
{
	double highest = pints[0];

	for (int index = 1; index < hours; index++)
	{
		if (pints[index] > highest)
		{
			highest = pints[index];
		}
	}

	return highest;
}

void displayInfo(int hours, double averagePints, double highestPints, double lowestPints)
{
	ofstream bloodOutFile;
	bloodOutFile.open("bloodResults.txt");
	bloodOutFile << "Report generated by Ricardo Diaz" << endl;
	bloodOutFile << "Blood drive period: " << hours << endl;
	bloodOutFile << "Average hours: " << averagePints << endl;
	bloodOutFile << "Highest Pints: " << highestPints << endl;
	bloodOutFile << "Lowest Pints: " << lowestPints << endl;
	bloodOutFile.close();

}

