/* Program: Lab 10 Program
	Author: Ricardo Diaz
	Class: CSCI 110
	Date: 11/9/23
	Description: Create the program for Lab 10.
	I certify that the code below is my own work.
	Exception(s): N/A
*/
#include <iostream>
#include <fstream>
#include <string>
#include <iomanip>

using namespace std;

void getPints(double pints[], int& hours);
double getAverage(double pints[], int hours);
double getHigh(double pints[], int hours, int& highIndex);
double getLow(double pints[], int hours, int& lowIndex);
void displayInfo(int hours, double averagePints, double highestPints, double lowestPints, int lowIndex, int highIndex);

const int MAX_HOURS = 24;

int main()
{

	double pints[MAX_HOURS] = { };
	double averagePints, highestPints, lowestPints;
	int lowIndex = 0;
	int highIndex = 0;
	int hours = 0;
	getPints(pints, hours);
	cout << "Hours: " << hours << endl;
	cout << "First Value: " << pints[0] << endl;
	cout << "Last Value: " << (hours > 0 ? pints[hours - 1] : 0) << endl;
	averagePints = getAverage(pints, hours);
	highestPints = getHigh(pints, hours, highIndex);
	lowestPints = getLow(pints, hours, lowIndex);
	displayInfo(hours, averagePints, highestPints, lowestPints, lowIndex, highIndex);

	return 0;
}

void getPints(double pints[], int& hours)
{
	ifstream bloodInFile;
	bloodInFile.open("bloodDrive.txt");

	if (!bloodInFile.is_open())
	{
		cout << "Error opening bloodDrive.txt" << endl;

		return;
	}
	hours = 0;
	int a;


	while (bloodInFile >> a && hours < MAX_HOURS)
	{
		pints[hours++] = a;

	}

	bloodInFile.close();

}

double getAverage(double pints[], int hours)
{
	double totalPints = 0;
	double averagePints;

	for (int counter = 0; counter < hours; counter++)
	{
		totalPints += pints[counter];
	}

	averagePints = totalPints / hours;
	return averagePints;
}

double getLow(double pints[], int hours, int& lowIndex)
{
	double lowest = pints[0];
	for (int index = 1; index < hours; index++)
	{
		if (pints[index] < lowest)
		{
			lowest = pints[index];
			lowIndex = index + 1;
		}
	}

	return lowest;
}


double getHigh(double pints[], int hours, int& highIndex)
{
	double highest = pints[0];
	for (int index = 1; index < hours; index++)
	{
		if (pints[index] > highest)
		{
			highest = pints[index];
			highIndex = index + 1;
		}
	}

	return highest;
}

void displayInfo(int hours, double averagePints, double highestPints, double lowestPints, int lowIndex, int highIndex)
{
	ofstream bloodOutFile;
	bloodOutFile.open("bloodResults.txt");
	bloodOutFile << fixed << setprecision(1);
	bloodOutFile << "Report generated by Ricardo Diaz" << endl;
	bloodOutFile << "Blood drive period: " << hours << endl;
	bloodOutFile << "Average hours: " << averagePints << endl;
	bloodOutFile << "Highest Pints: " << highestPints << " (hour " << highIndex << ")" << endl;
	bloodOutFile << "Lowest Pints: " << lowestPints << " (hour " << lowIndex << ")" << endl;
	bloodOutFile.close();

}
